### PR TITLE
readded the Appid page

### PR DESCRIPTION
**Pull request by ValentinKruegl**
Last pull request broke the page for AppIDs
now i added back the page and the images

### CODE REVIEW

**Review by jnweiger — COMMENTED** [review]
Looks good to me!

**Review by phil-davis — COMMENTED** [review]
English looks OK. I have not checked that all the image links are valid and other document placement in the hierarchy etc. are correct.

**Comment by ValentinKruegl** [comment]
> I have not checked that all the image links are valid

now they are, good catch

**Review by santanair — APPROVED** [review]
looks good

**Pull request merged**
